/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_split.c                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: falves-b <falves-b@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/11/09 16:09:40 by falves-b          #+#    #+#             */
/*   Updated: 2022/12/14 11:38:33 by falves-b         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libft.h"

static char	*ft_strchrnul(const char *s, int c)
{
	char	*ptr;

	ptr = ft_strchr(s, c);
	if (!ptr)
		ptr = ft_strchr(s, '\0');
	return (ptr);
}

char	**ft_split(char const *s, char c)
{
	char	**result;
	char	**result_start;
	char	*ptr;

	if (!s)
		return (NULL);
	result = ft_calloc(ft_strlen(s) / 2 + 1, sizeof(char *));
	result_start = result;
	if (!result || !ft_strlen(s))
		return (result_start);
	while (1)
	{
		if (*s != c)
		{
			if (*s == '\0')
				break ;
			ptr = ft_strchrnul(s, c);
			*result = ft_calloc(ptr - s + 1, 1);
			ft_strlcpy(*result++, s, ptr - s + 1);
			s = ptr;
		}
		else
			s++;
	}
	return (result_start);
}
/* #include <stdio.h>

int main()
{
	//this src has 3000 words
	char	*src = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget tellus dui. Vivamus lobortis erat sit amet mauris mattis, non venenatis dui malesuada. Maecenas sed metus volutpat, convallis lorem non, eleifend enim. Nunc tristique enim eu pharetra ullamcorper. Maecenas eget dolor risus. Nullam ornare molestie purus eu fermentum. Integer a mauris non mi posuere porta quis a velit. In quis enim in diam imperdiet convallis. Nullam luctus aliquet libero, sed commodo felis aliquet elementum. Vivamus molestie eu neque eu tincidunt. Aliquam semper justo lobortis arcu fermentum, vitae laoreet lorem pharetra. Morbi suscipit semper est at eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec interdum metus neque, vel vestibulum diam placerat quis. Proin vel elit vel odio vulputate mattis. Morbi feugiat tortor vel leo tincidunt, ac tristique dolor dapibus."
	" Donec nec sodales tellus, quis finibus est. Phasellus sed semper quam, non sagittis eros. Mauris fermentum orci vel vehicula egestas. Duis auctor suscipit ligula. Etiam blandit, odio sed rutrum luctus, nulla ligula gravida libero, eu scelerisque velit libero sit amet erat. Nulla et elit nec nunc luctus ultricies. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur ultricies, orci non dignissim mollis, velit libero porta enim, ac porta turpis nunc vel massa. Aenean facilisis dignissim quam et ultricies. Curabitur et quam vel libero varius finibus a id tortor. Donec luctus diam ipsum, vitae pharetra ipsum varius id. Nunc vestibulum sagittis mi a placerat. Nulla consectetur scelerisque nunc, sit amet mollis magna porta sed. In hac habitasse platea dictumst. Aliquam facilisis diam ipsum, ac congue nisl cursus sed. Mauris pulvinar pharetra augue at posuere."
	" Vivamus non egestas velit. Ut commodo eu risus id rutrum. Ut vitae gravida nibh. Ut convallis mi in egestas aliquam. Fusce congue mi vel justo ultrices, id pellentesque felis aliquam. Nam eu euismod ipsum, in elementum tellus. Nam tincidunt eros lacus, ut fermentum orci varius nec. Etiam vulputate ut ipsum eget condimentum. Curabitur purus erat, suscipit in euismod vulputate, iaculis efficitur turpis. Maecenas bibendum malesuada justo, semper tincidunt sem consectetur eu."
	" Duis volutpat eros a magna fringilla, in rhoncus ex imperdiet. Donec id placerat quam, quis venenatis felis. Duis placerat dolor ut vestibulum tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed pellentesque aliquam accumsan. Proin nec hendrerit est, et vulputate urna. Fusce sodales eros eu diam convallis, eget luctus urna aliquet. Maecenas pulvinar risus vitae convallis eleifend. Proin luctus malesuada urna, sit amet dictum elit egestas eget. Duis scelerisque turpis orci. Vivamus lorem leo, congue in massa ornare, tempus lacinia lectus. Praesent convallis purus magna, et congue sapien cursus a. Nullam vel arcu lacinia, lacinia mauris non, porttitor neque. Suspendisse malesuada, arcu et interdum ultrices, tortor tortor venenatis nisl, eget porttitor nisi arcu id elit. Suspendisse condimentum ornare tellus, ut vulputate nisl mollis vitae."
	" Donec nec pellentesque lectus. Donec tristique vitae lorem sed rutrum. Quisque imperdiet risus vel maximus accumsan. Curabitur porttitor luctus scelerisque. Mauris aliquet sed risus in tempus. Donec dapibus, arcu a suscipit aliquet, orci felis fringilla dolor, et ornare leo orci quis velit. Nam sodales suscipit erat, at rutrum ipsum. Sed a tempus erat."
	" Nulla vehicula orci at metus mattis, porttitor pellentesque justo auctor. Proin scelerisque varius dolor, a sodales nulla malesuada et. Etiam elementum at lorem ut lobortis. Morbi ultricies lacus mattis tellus egestas, at suscipit felis hendrerit. Nam sed libero a magna luctus dapibus. Curabitur consequat, enim sit amet malesuada porttitor, nunc purus feugiat magna, id ultricies est tellus ultricies magna. Duis nec purus maximus felis euismod bibendum eu a felis. Duis viverra malesuada interdum. Nullam dapibus velit vitae nisl semper efficitur."
	" Nam tristique auctor mauris, in vulputate nunc rutrum eget. Vestibulum quis enim a lacus tincidunt vestibulum. Mauris justo nulla, accumsan at nibh id, mattis ultrices purus. Vestibulum suscipit lacus nibh, non iaculis arcu aliquet vel. Vestibulum fringilla vulputate elit. Vestibulum facilisis turpis eu arcu vulputate, nec laoreet lectus dapibus. Maecenas lorem lectus, volutpat vel facilisis id, luctus quis risus. Sed lacinia, sem at laoreet semper, neque est cursus ex, vitae blandit magna magna vitae lacus. Maecenas ullamcorper eget dolor vitae vehicula."
	" Morbi volutpat turpis eu hendrerit lobortis. Sed viverra nec est sollicitudin scelerisque. Curabitur venenatis varius ligula, luctus feugiat est scelerisque ac. In non tellus et odio euismod porta ut a est. In eu vestibulum erat, sit amet viverra lacus. Maecenas rutrum, nulla vitae elementum facilisis, libero neque placerat nisl, vel tempor odio ex eget nisl. Duis volutpat leo arcu, ut semper risus tincidunt quis. Nulla vitae posuere tortor."
	" Aenean laoreet tellus sit amet magna viverra interdum. Donec sem lacus, mollis id arcu sit amet, rhoncus consequat ex. Ut aliquam in dolor at rutrum. Pellentesque sit amet magna libero. Nullam est nunc, congue et molestie id, ullamcorper sit amet neque. Aenean sed dolor augue. Suspendisse eu viverra tellus. In ullamcorper ex erat, sed ultricies arcu ornare ac. Donec aliquam convallis odio a sodales. Nulla imperdiet dapibus urna, ac consectetur eros lobortis ac. Nulla eget tellus purus. Maecenas id vehicula lectus, a vehicula ex. Fusce hendrerit pellentesque sapien, non condimentum augue euismod et. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos."
	" Sed facilisis aliquam dui, nec luctus est semper vitae. Proin varius eu quam malesuada faucibus. Curabitur pulvinar odio massa, vitae ultrices massa rutrum varius. Integer quis augue eget erat tempus posuere. Vivamus egestas lorem ac quam dapibus, ac facilisis mi ultricies. Aenean sollicitudin tristique massa, nec cursus nisi hendrerit eget. Aliquam et posuere felis, nec viverra tellus. Aenean in nisl quam."
	" Maecenas quis libero odio. Cras est diam, pharetra non sem eget, cursus condimentum eros. Nullam dapibus viverra ligula vel hendrerit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam velit est, iaculis eu posuere vel, accumsan non lacus. Phasellus malesuada faucibus metus. Nullam vel ornare tortor. Vivamus ac augue at urna bibendum varius. Maecenas laoreet ac velit eu ultricies. Etiam fringilla tincidunt quam quis commodo. Maecenas vulputate enim et velit rhoncus, a semper elit accumsan. Fusce sit amet risus sed ipsum maximus commodo. Nam eget fringilla mi. Etiam laoreet nisl in orci fermentum hendrerit. Maecenas tempus et purus ac imperdiet."
	" Sed in purus id massa hendrerit facilisis quis sed massa. Morbi bibendum at leo eget tristique. Sed pretium eros at metus facilisis commodo. Ut id bibendum lacus, nec ullamcorper arcu. Nullam pharetra gravida consectetur. Proin vitae eleifend turpis, eu pharetra nisl. Fusce venenatis dignissim justo quis feugiat. Nunc urna est, consequat porta interdum non, tempus ac nunc. Aliquam semper nisi lorem, ut venenatis neque luctus faucibus. Sed lobortis velit quis sapien eleifend placerat."
	" Sed at massa et tellus ultricies commodo non elementum mi. Donec quis suscipit neque. Quisque quis lacus nibh. Pellentesque ac felis non neque tempor luctus. Nunc id ipsum eu metus interdum suscipit. Suspendisse pulvinar ligula ligula, at vehicula neque sagittis sit amet. Maecenas congue ultricies velit, in rhoncus nulla euismod ac. Aliquam erat volutpat. Nulla hendrerit id diam condimentum scelerisque. Donec vel fermentum augue. Vestibulum luctus sem eros, quis ultricies eros tempus in. Maecenas placerat, sapien id interdum lacinia, odio leo malesuada enim, ornare placerat mauris elit nec mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit."
	" Suspendisse luctus ante vitae nisl sagittis, sed interdum tortor imperdiet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris at magna ut sem eleifend dignissim ut mollis lorem. Praesent sit amet ex pretium velit venenatis accumsan. Suspendisse dignissim fringilla congue. Duis feugiat ornare interdum. Sed luctus lorem ut gravida egestas. Vivamus laoreet scelerisque auctor. Praesent at facilisis nulla."
	" Sed ante ipsum, rutrum vel aliquet venenatis, tempor a odio. In ut ultricies tortor. Sed mollis faucibus nunc. Mauris sed est ac eros facilisis consequat ut ut diam. In hac habitasse platea dictumst. Integer lobortis diam eleifend lorem fringilla scelerisque. Proin suscipit dignissim aliquam. Sed auctor tortor id varius efficitur. Ut porta non arcu ac tempus."
	" Cras vehicula iaculis iaculis. Nam eu purus sit amet nunc aliquam sagittis. Nam pretium bibendum ipsum lacinia suscipit. Phasellus porttitor, arcu vel porttitor tempor, quam ipsum consequat dolor, eget mattis ante arcu et purus. Praesent et magna rutrum odio euismod tempus sed sed ex. Suspendisse et odio ut turpis molestie tristique sit amet in nibh. Proin id tellus vel nunc imperdiet porta vitae nec enim. Sed eget nisl nec est finibus aliquam eu sit amet dolor. Sed in odio vel mauris hendrerit suscipit. Nullam id dui pellentesque, posuere nulla in, tristique diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vulputate purus vitae venenatis dictum. Fusce vel congue diam. Nulla ac velit varius libero sagittis tempor. Ut eget urna ligula. Nunc suscipit eros malesuada, ultricies tellus at, sagittis ipsum."
	" Sed et semper nibh, nec porttitor velit. Vivamus at est imperdiet, molestie felis suscipit, molestie sapien. Pellentesque aliquet eros vel lorem finibus, eu gravida nisi convallis. Phasellus non ante sed diam suscipit tincidunt. In a dapibus nunc. Quisque id urna gravida, bibendum nisi nec, elementum justo. Nam ultrices tincidunt sapien, et viverra lacus vulputate ut. Pellentesque vitae ligula tellus. Proin condimentum viverra justo sit amet efficitur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;"
	" Maecenas nec eros justo. Sed semper nulla non felis condimentum cursus. Ut malesuada sem a efficitur lacinia. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas a neque risus. Donec lacinia lacus quis erat posuere rutrum. Etiam efficitur diam vel orci pellentesque tempor vel et metus. Proin eu leo quis tellus gravida cursus quis sed justo. Sed eget nibh sem. Quisque euismod lacinia dolor sit amet sagittis. Praesent sit amet turpis in mi cursus volutpat. Sed condimentum orci venenatis auctor dapibus. In hendrerit tempus lectus a pharetra. Ut et felis elit. Pellentesque sagittis ligula magna, a placerat massa molestie ac. Etiam nibh urna, porta vel euismod eget, lacinia et nulla."
	" In ultrices quam in metus sollicitudin, vitae molestie ex viverra. Sed pulvinar eget neque eget semper. Nam vestibulum sodales eros vitae placerat. Aliquam erat volutpat. Proin et felis nulla. Proin congue vitae quam eu sollicitudin. Praesent blandit feugiat ante. Vestibulum sed lectus ultrices, dignissim sapien scelerisque, faucibus justo. Cras semper tellus non vulputate pretium. Donec vehicula ipsum a erat dictum, sit amet iaculis tortor rutrum."
	" Sed scelerisque enim non tortor ultrices pretium a ut lacus. In varius aliquam dolor, non fermentum risus vestibulum vel. Nullam a gravida lectus. Vivamus convallis mi eros, et ultrices quam consectetur mattis. Aenean tincidunt, ipsum sit amet dignissim rutrum, erat quam euismod felis, quis dignissim nisl libero nec augue. Sed velit felis, consectetur sit amet erat eu, consequat varius nisi. Aenean rhoncus odio nibh, sit amet tincidunt lectus pulvinar vitae. Ut fringilla vel ipsum gravida laoreet. Sed semper eleifend ante at volutpat. Vestibulum consequat magna fringilla dui consectetur posuere. Vivamus fermentum bibendum tellus eget luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos."
	" Suspendisse tempor, tellus a auctor malesuada, nisl massa tincidunt ex, ac facilisis orci dui et enim. Sed id justo vel lectus dapibus posuere at ac purus. Pellentesque tincidunt faucibus gravida. Nulla facilisi. Cras ac nibh quis neque porta lobortis in quis lorem. Cras semper nisl ligula, sed ultrices risus sollicitudin ut. Curabitur sed lacus quam. Integer vitae tincidunt ante. Proin sapien eros, imperdiet euismod lacus a, sollicitudin posuere magna. In faucibus imperdiet neque, non dapibus massa dapibus non. Donec sit amet convallis elit, eu dictum lorem. Nulla consectetur dapibus odio, non congue augue porta et. Vivamus et ultrices diam. In non ultricies urna, non dapibus velit. Aenean suscipit ante vel elit malesuada, a sollicitudin mauris feugiat."
	" Ut dapibus ligula sit amet ornare mattis. Donec nec velit fringilla, molestie est id, dapibus odio. Praesent et vulputate erat. Sed ullamcorper metus nunc, sed viverra diam convallis vitae. Etiam ac dui ac velit ullamcorper dictum at nec diam. Curabitur feugiat, diam non posuere volutpat, justo tortor interdum nulla, eu sodales justo turpis nec eros. Vivamus iaculis odio in auctor luctus. Integer gravida nec leo vel rhoncus. In vel neque mattis, ullamcorper mauris a, consectetur augue. Donec eros turpis, malesuada quis facilisis sed, sollicitudin sit amet purus."
	" Duis tempus est metus, nec dignissim ante sollicitudin quis. Donec non tincidunt nibh. In in molestie lacus. Proin ornare mauris ac diam aliquam laoreet. Aenean non ultrices ligula. Cras volutpat porta augue vitae dignissim. Donec gravida augue vel luctus volutpat. Suspendisse tempus, dui id rhoncus fermentum, mauris leo varius tortor, vel volutpat justo magna et velit."
	" Pellentesque vitae ex a erat tempor aliquam. Nam sit amet auctor elit. Fusce auctor vehicula ante, a efficitur neque rutrum ac. Aenean luctus metus id augue pretium aliquam. Duis nisi neque, dapibus eget elit at, finibus placerat lectus. Mauris quis mauris eu eros consectetur aliquet interdum vel eros. Curabitur posuere facilisis tortor in pulvinar. Nunc vitae felis sed massa auctor mollis a ut lectus. Nullam non dolor id est dapibus rutrum. Praesent mollis massa sit amet ex faucibus vestibulum. Sed porttitor sed nisi a congue."
	" Mauris sed turpis at purus condimentum fermentum sit amet quis ipsum. Nunc mollis eros metus. Nullam convallis dui pulvinar aliquet ullamcorper. Nulla ornare, felis id mollis cursus, ligula erat pretium justo, vitae aliquam turpis ante id justo. Aliquam porttitor rhoncus sem, ac rhoncus nisi feugiat sit amet. Fusce tincidunt, urna et iaculis ornare, arcu eros commodo purus, nec sollicitudin ipsum leo a urna. Etiam eu ultricies turpis, ut elementum velit. Cras feugiat, quam eget posuere varius, massa magna dignissim ligula, sit amet malesuada ex ipsum a purus. Donec mollis libero quis quam tristique dignissim. Curabitur a lorem vel enim maximus dictum eu vitae eros. Proin nec mauris magna. Aenean eu suscipit erat. Donec laoreet mauris sit amet lorem convallis, non interdum eros euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce interdum risus ut dui elementum, et cursus turpis tempor."
	" Nam quis posuere turpis. Nullam erat enim, semper eu bibendum nec, mattis sed risus. Nulla lobortis magna nisl. Sed semper neque non malesuada eleifend. Nam laoreet odio at imperdiet aliquet. Morbi nec felis mattis, tempus nulla ut, tincidunt ipsum. Fusce tempor pulvinar ligula, eu facilisis nulla dignissim id. In in libero ullamcorper, molestie nibh sed, varius felis."
	" Nullam pharetra vel enim ac imperdiet. In ipsum eros, volutpat eget purus non, posuere volutpat ante. Etiam lacus velit, semper vitae orci eu, posuere hendrerit ipsum. Morbi bibendum felis eu tempus molestie. Donec id erat eros. Nulla viverra mollis odio, in maximus nisi aliquam in. Etiam non hendrerit nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas magna enim, vestibulum ac congue sed, tincidunt sed neque."
	" Sed varius non metus sit amet cursus. Nulla convallis enim in dapibus vestibulum. Nulla quis eros hendrerit turpis accumsan venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut lobortis quis lorem eget semper. Donec venenatis, elit nec aliquet fringilla, tellus ligula ornare mi, at tincidunt est nibh sit amet est. Quisque id tellus id massa laoreet rutrum. Maecenas id viverra libero, vitae commodo ipsum. Sed at elementum dolor. Cras pretium ac risus id ullamcorper. In dignissim pretium malesuada. Etiam sit amet lacus feugiat, congue neque at, lacinia massa. Donec tellus eros, ullamcorper at sapien at, molestie mollis eros. Nulla facilisi. Etiam rutrum diam at elementum luctus. Donec efficitur sapien ut rutrum varius."
	" Donec eleifend egestas ullamcorper. Quisque iaculis iaculis leo sit amet convallis. Fusce sed ullamcorper ante. Pellentesque lacus lorem, auctor et lorem et, porta laoreet tortor. Nulla at nisi fringilla dolor tincidunt porttitor id ut est. Nullam vehicula, magna et tristique sagittis, nunc ex posuere nisi, volutpat semper dolor elit ac mauris. In finibus, purus sit amet porta porta, arcu risus feugiat justo, et porta erat orci mattis orci. Cras efficitur felis sed eros aliquet, a rutrum sapien viverra. Suspendisse eget lectus elit. Integer a tincidunt magna."
	" Etiam in ullamcorper enim. Nullam rhoncus mattis nisi ut mattis. Vestibulum varius, lectus vel dapibus ultrices, urna massa blandit elit, vitae maximus justo mi in nulla. Praesent consectetur purus sapien, non hendrerit sapien efficitur porta. Maecenas hendrerit augue nec pellentesque consectetur. Nulla tortor dui, eleifend et lacus in, venenatis tristique ipsum. Vestibulum aliquam consectetur quam at facilisis. Nulla facilisi. Nam ut mauris in eros gravida viverra. Mauris vehicula sagittis ipsum ac vulputate."
	" Quisque laoreet scelerisque est vitae fermentum. Donec sagittis non odio vitae vestibulum. Nunc ac diam sodales, tincidunt diam et, mollis arcu. In turpis elit, rhoncus non risus id, commodo sodales risus. Vivamus efficitur consequat malesuada. Sed placerat neque sit amet lectus ultrices luctus. Donec tincidunt egestas sem, vel rhoncus enim placerat sit amet. Aliquam erat volutpat. Phasellus vitae consectetur nulla. Nullam tincidunt ullamcorper semper. Fusce nec magna sollicitudin, eleifend purus in, fermentum odio. Nullam vestibulum mi ornare, blandit nisl ut, semper lorem."
	" Duis vehicula ipsum quis nulla sagittis, sit amet rhoncus tortor ullamcorper. Nulla sit amet auctor quam, sed dictum massa. Pellentesque porttitor consectetur lorem convallis consequat. Pellentesque fermentum dignissim nulla, a interdum sem aliquet auctor. Etiam congue nibh ex, ut gravida nulla ultrices vitae. Aenean suscipit posuere turpis, nec mollis leo convallis ut. Suspendisse interdum lacus in metus ultrices, eget commodo metus venenatis."
	" Donec fermentum ut purus nec bibendum. Aenean eu arcu cursus, accumsan ex non, rhoncus diam. Sed placerat laoreet nisl, sit amet scelerisque lacus laoreet ullamcorper. Donec et lacinia elit. Quisque metus libero, tempus a tempor vel, pretium quis nulla. Donec maximus est metus, a posuere ante congue et. Curabitur non nisl sit amet nisi posuere interdum ac et nisl. Donec ullamcorper ipsum sit amet eleifend sagittis. In condimentum dapibus magna, sit amet consequat velit tincidunt ut. Proin feugiat accumsan magna, scelerisque semper mauris elementum in. In finibus id metus vitae iaculis. Suspendisse potenti. Nulla facilisi. Donec finibus hendrerit leo at congue. Aliquam porta condimentum ligula ut aliquam."
	" Morbi dignissim pulvinar tellus pellentesque sagittis. Quisque malesuada euismod nisi quis hendrerit. Vestibulum pulvinar, orci non vestibulum cursus, urna justo cursus ex, vitae varius odio eros sed ipsum. Sed a ullamcorper risus, et cursus sem. Vestibulum in est hendrerit ipsum bibendum bibendum ac ut risus. Fusce ultrices est vitae varius. ";
	char	**result;
	int		count;

	count = 0;
	result = ft_split(src, ' ');
	while (*result)
	{
		printf("word = %s\n", *result);
		result++;
		count++;
	}
	printf("count = %i\n", count);
}
 */